spring.application.name=admin-service

server.port=8084

# Railway Cloud MySQL Connection
spring.datasource.url=jdbc:mysql://${DB_HOST:reseau.proxy.rlwy.net}:${DB_PORT:34643}/admin_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:ttNiTnfDSzzsiFIcrEYKynIkAiKkqOsM}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Eureka
eureka.client.service-url.defaultZone=http://${EUREKA_HOST:localhost}:8761/eureka

# JWT
jwt.secret=bXlzZWNyZXRrZXlteXNlY3JldGtleW15c2VjcmV0a2V5MTIzNDU2Nzg5MDEyMw==

# Service URLs
auth.service.url=http://${AUTH_HOST:localhost}:8081
donation.service.url=http://${DONATION_HOST:localhost}:8082
request.service.url=http://${REQUEST_HOST:localhost}:8083
